// Auto-generated by map editor - 2025-08-12T21:50:00.777Z
// Do not edit manually - changes will be overwritten
// Multi-Circle Collision System

const ISLANDS_DATA = [
  {
    "name": "Saint Kitts Island",
    "x": 2000,
    "y": 1500,
    "radius": 342.76669409945464,
    "collisionCircles": [
      {
        "x": 0,
        "y": 0,
        "radius": 280
      },
      {
        "x": -160,
        "y": -155,
        "radius": 120
      },
      {
        "x": 140,
        "y": 145,
        "radius": 100
      },
      {
        "x": -50,
        "y": 100,
        "radius": 80
      }
    ],
    "imageFilename": "Saint_Kitts.png"
  },
  {
    "name": "Nevis Island",
    "x": 2382.917579810254,
    "y": 2131.098680133246,
    "radius": 358.3069198510586,
    "collisionCircles": [
      {
        "x": -4.874034072530776,
        "y": 126.85913743787796,
        "radius": 486
      }
    ],
    "imageFilename": "Nevis.png"
  }
];

// Export for both CommonJS and ES6 modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = ISLANDS_DATA;
}
